// <auto-generated />
using AltcoinTrader.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AltcoinTrader.Migrations
{
    [DbContext(typeof(ApplicationDBcontext))]
    [Migration("20250627101708_InitialCreates2")]
    partial class InitialCreates2
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AltcoinTrader.Models.Coin", b =>
                {
                    b.Property<int>("CoinID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CoinID"));

                    b.Property<string>("CoinName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("CoinPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("CoinTicker")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CoinVote")
                        .HasColumnType("int");

                    b.HasKey("CoinID");

                    b.ToTable("Coins");
                });
#pragma warning restore 612, 618
        }
    }
}
